Repository microsoft/mu_silicon_intel_tiano, pull requests merged in 2023-02, with the labels that each got.

#44 .azurepipelines: Add support for new artifacts_identifier param
  .azurepipelines/Matrix-Build-Job.yml
Labels: impact:non-functional, impact:breaking-change, type:enhancement

#49 Remove VS2015 and VS2017 Stack Cookie Support from Package DSC Files
  IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dsc
  IntelSiliconPkg/IntelSiliconPkg.dsc
Labels: impact:non-functional

#53 IntelFsp2Pkg.dsc: Add stack cookie support libs
  IntelFsp2Pkg/IntelFsp2Pkg.dsc
Labels: type:bug, impact:non-functional

#52 Add CodeQL Stuart parameter to this repo
  .pytool/CISettings.py
Labels: impact:non-functional, type:enhancement
