Repository microsoft/mu_silicon_intel_tiano, pull requests merged in 2024-01, with the labels that each got.

#167 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: impact:non-functional, semver:patch

#175 Update pip-requirements.txt
  pip-requirements.txt
Labels: type:dependencies, impact:non-functional

#170 Updated CISettings.py to use the edk2toolext codeql helpers
  .github/workflows/codeql.yml
  .pytool/CISettings.py
Labels: impact:testing, impact:non-functional
